import { useState, useEffect, useCallback, useRef } from 'react';
import type { FeatureNode } from '../types/feature';
import { useTaskStore } from '../store/taskStore';

interface Props {
  projectPath: string | null;
  onSelectFeature: (node: FeatureNode | null) => void;
  selectedId: string | null;
  onFeaturesLoaded: (features: FeatureNode[]) => void;
}

const COL = {
  surfaceVariant: '#282a2d',
  onSurface: '#e3e2e6',
  onSurfaceVariant: '#c4c7c5',
  outline: '#444746',
  primary: '#8ab4f8',
  yellow: '#d29922',
};

export default function FeatureList({ projectPath, onSelectFeature, selectedId, onFeaturesLoaded }: Props) {
  const [features, setFeatures] = useState<FeatureNode[]>([]);
  const [loading, setLoading] = useState(false);
  const [polling, setPolling] = useState(false);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const autoGenerated = useRef<string | null>(null);

  // Reset on project change
  useEffect(() => { autoGenerated.current = null; }, [projectPath]);

  const loadFeatures = useCallback(async () => {
    if (!projectPath) return;
    try {
      const res = await fetch(`/api/v1/features?project_path=${encodeURIComponent(projectPath)}`);
      const data = await res.json();
      const list = data.features || [];
      setFeatures(list);
      onFeaturesLoaded(list);
      // Auto-generate only if DB is empty for this project
      if (list.length === 0 && projectPath !== autoGenerated.current) {
        autoGenerated.current = projectPath;
        handleGenerate();
      }
    } catch { /* */ }
  }, [projectPath, onFeaturesLoaded]);

  useEffect(() => { loadFeatures(); }, [loadFeatures]);

  // Poll for changes from bottom agent — incremental update
  useEffect(() => {
    if (!projectPath) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`/api/v1/changes/pending?project_path=${encodeURIComponent(projectPath)}`);
        const data = await res.json();
        if (data.has_pending && data.items?.length > 0) {
          setPolling(true);
          // Incremental update based on specific changes
          const item = data.items[0];
          await fetch('/api/v1/features/incremental-update', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              project_path: projectPath,
              change_summary: item.summary || '',
              files_changed: item.files_changed || [],
            }),
          });
          // Reload to get updated features
          await loadFeatures();
          setPolling(false);
        }
      } catch { /* */ }
    }, 8000);
    return () => clearInterval(interval);
  }, [projectPath]);

  const handleGenerate = async () => {
    if (!projectPath) return;
    setLoading(true);
    const taskId = `analyze_top_${Date.now()}`;
    useTaskStore.getState().addTask({ id: taskId, type: 'analyze', label: 'Analyze project features', status: 'running', startedAt: Date.now(), detail: 'Reading code...' });
    try {
      let fileTree: any[] = [];
      try { fileTree = await window.codeatlas.file.listDirectory(projectPath); } catch { /* */ }
      const res = await fetch('/api/v1/features/analyze-top', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ project_path: projectPath, file_tree: fileTree }),
      });
      const data = await res.json();
      if (data.features?.length) {
        setFeatures(data.features);
        onFeaturesLoaded(data.features);
        onSelectFeature(null);
        useTaskStore.getState().updateTask(taskId, { status: 'done', detail: `${data.features.length} features found` });
      } else {
        useTaskStore.getState().updateTask(taskId, { status: 'error', detail: 'No features generated' });
      }
    } catch (e: any) {
      useTaskStore.getState().updateTask(taskId, { status: 'error', detail: e.message || 'Failed' });
    }
    setLoading(false);
    // Remove done tasks after 3s
    setTimeout(() => useTaskStore.getState().removeTask(taskId), 3000);
  };

  return (
    <div className="flex flex-col h-full" style={{ background: COL.surfaceVariant }}>
      <div className="flex items-center justify-between px-3 py-1.5 border-b shrink-0" style={{ borderColor: COL.outline }}>
        <span className="text-[10px] font-medium uppercase tracking-wide" style={{ color: COL.onSurfaceVariant }}>Features</span>
        <div className="flex items-center gap-1.5">
          {polling && <span className="text-[9px] animate-pulse" style={{ color: COL.yellow }}>sync</span>}
          <button
            onClick={handleGenerate}
            disabled={(!features.length && loading) || !projectPath}
            className="text-[9px] p-1 rounded-full transition-colors hover:opacity-80 disabled:opacity-30"
            style={{ background: '#003a75', color: COL.primary }}
            title={features.length > 0 ? 'Refresh' : 'Analyze'}>
            {features.length > 0 ? (
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"
                className={loading ? 'animate-spin' : ''}>
                <path d="M1 4v6h6M23 20v-6h-6" /><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15" />
              </svg>
            ) : (
              loading ? '...' : 'Analyze'
            )}
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        {features.length === 0 && (
          <div className="flex flex-col items-center justify-center py-8 gap-3">
            {loading ? (
              <>
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <div key={i} className="w-1.5 h-1.5 rounded-full animate-pulse-dot"
                      style={{ background: COL.primary, animationDelay: `${i * 0.2}s` }} />
                  ))}
                </div>
                <div className="text-[10px] text-center" style={{ color: '#5c6166' }}>
                  Analyzing project structure...
                </div>
              </>
            ) : (
              <button onClick={handleGenerate} className="text-[10px] px-3 py-1 rounded-full transition-colors hover:bg-white/10"
                style={{ border: `1px solid ${COL.outline}`, color: COL.primary }}>
                Analyze
              </button>
            )}
          </div>
        )}
        {/* Recursive tree nodes */}
        {features.map((node) => (
          <TreeNode
            key={node.id}
            node={node}
            depth={0}
            expanded={expanded}
            selectedId={selectedId}
            onToggle={(id) => setExpanded((prev) => {
              const next = new Set(prev);
              next.has(id) ? next.delete(id) : next.add(id);
              return next;
            })}
            onSelect={onSelectFeature}
          />
        ))}
      </div>
    </div>
  );
}

/* ── Recursive tree node ── */
const LV_DOT: Record<number, string> = { 0: '#8b949e', 1: '#8ab4f8', 2: '#3fb950', 3: '#d29922' };

function TreeNode({ node, depth, expanded, selectedId, onToggle, onSelect }: {
  node: FeatureNode; depth: number; expanded: Set<string>; selectedId: string | null;
  onToggle: (id: string) => void; onSelect: (node: FeatureNode) => void;
}) {
  const hasChildren = (node.children && node.children.length > 0) || (!node.generated && node.level < 3);
  const isExpanded = expanded.has(node.id);
  const isSelected = selectedId === node.id;
  const padLeft = 12 + depth * 16;

  return (
    <div>
      <button
        onClick={() => {
          if (hasChildren) { onToggle(node.id); }
          onSelect(node);
        }}
        className={`w-full text-left py-1.5 border-b transition-colors hover:bg-white/[0.03] ${isSelected ? 'bg-white/[0.06]' : ''}`}
        style={{ paddingLeft: padLeft, paddingRight: 12, borderColor: '#30323440' }}>
        <div className="flex items-center gap-1.5">
          {/* Expand/collapse arrow */}
          {hasChildren && (
            <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="#5c6166" strokeWidth="2"
              style={{ transform: isExpanded ? 'rotate(90deg)' : 'rotate(0deg)', transition: 'transform 0.15s' }}>
              <path d="M9 18l6-6-6-6" />
            </svg>
          )}
          {!hasChildren && <span className="w-2 shrink-0" />}
          <div className="w-1.5 h-1.5 rounded-full shrink-0" style={{ background: LV_DOT[node.level] || '#8e918f' }} />
          <span className="text-[11px] font-medium truncate" style={{ color: '#c9d1d9' }}>{node.label}</span>
          {node.children?.length > 0 && !isExpanded && (
            <span className="ml-auto text-[9px]" style={{ color: '#5c6166' }}>{node.children.length}</span>
          )}
        </div>
      </button>
      {/* Children */}
      {isExpanded && node.children?.map((child) => (
        <TreeNode
          key={child.id}
          node={child}
          depth={depth + 1}
          expanded={expanded}
          selectedId={selectedId}
          onToggle={onToggle}
          onSelect={onSelect}
        />
      ))}
    </div>
  );
}
